version: '3.4'

services:
  roots-mariadb:
    image: mariadb:10.3
    container_name: roots-mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
      - ./.tmp/mysqld:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roots
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  roots-django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: roots-django
    restart: always
    volumes:
      - .:/htdocs/www
    depends_on:
      - roots-mariadb
    links:
      - roots-mariadb
    command:
      - bash
      - -c
      - |
        ./docs/dev/wait_for_it.sh roots-mariadb:3306
        make docker-cmd

  roots-nginx:
    image: nginx:stable
    container_name: roots-nginx
    restart: always
    volumes:
      - ./docs/dev/nginx:/etc/nginx/conf.d:ro
      - ./docs/dev/cert:/etc/nginx/cert/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - roots-django
    links:
      - roots-django
