version: '3.4'

services:
  roots-postgresql:
    image: postgres:12.0
    container_name: roots-postgresql
    restart: always
    volumes:
      - ./.tmp/rdbms:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: roots
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test

  roots-django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: roots-django
    restart: always
    volumes:
      - .:/htdocs/www
    depends_on:
      - roots-postgresql
    links:
      - roots-postgresql
    command:
      - bash
      - -c
      - |
        ./docs/dev/wait_for_it.sh roots-postgresql:5432
        make docker-cmd

  roots-nginx:
    image: nginx:stable
    container_name: roots-nginx
    restart: always
    volumes:
      - ./docs/dev/nginx:/etc/nginx/conf.d:ro
      - ./docs/dev/cert:/etc/nginx/cert/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - roots-django
    links:
      - roots-django
