# Generated by Django 2.2.6 on 2019-10-26 18:17

from django.db import migrations, models

import apps.domains.metadata.models
import libs.django.db.models.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name_kor', models.CharField(max_length=32, verbose_name='한글이름')),
                ('name_foreign', models.CharField(blank=True, max_length=32, null=True, verbose_name='외국이름')),
                ('name_original_kor', models.CharField(blank=True, max_length=32, verbose_name='본명-한글')),
                ('name_original_foreign', models.CharField(blank=True, max_length=32, verbose_name='본명-외국어')),
                ('gender', models.IntegerField(choices=[(0, '남자'), (1, '여자'), (65535, '기타')], verbose_name='성별')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=apps.domains.metadata.models._people_profile_img_upload_to,
                                                  verbose_name='사진')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='사망날짜')),
            ],
            options={
                'verbose_name': '인물',
                'verbose_name_plural': '인물목록',
                'db_table': 'people',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
    ]
