# Generated by Django 2.2.6 on 2019-10-30 15:28

import apps.domains.metadata.models
from django.db import migrations, models
import django.db.models.deletion
import libs.django.db.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='제목')),
                ('title_kor', models.CharField(max_length=255, verbose_name='한국제목')),
                ('content_type', models.IntegerField(choices=[(0, '영화'), (1, '일본드라')], verbose_name='작품 종')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to=apps.domains.metadata.models._content_cover_img_upload_to, verbose_name='작품사진')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='방송시작날짜')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='방송종료날짜')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품목록',
                'db_table': 'content',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='people',
            name='name_foreign',
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='이름'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='제목')),
                ('title_kor', models.CharField(max_length=255, verbose_name='한글제목')),
                ('order', models.IntegerField(default=1, help_text='이 숫자를 바탕으로 volume 을 노출한다. 단편의 경우 1이다.', verbose_name='순서')),
                ('broadcast_date', models.DateField(blank=True, null=True, verbose_name='방송월일')),
                ('viewer_ratings', models.IntegerField(blank=True, null=True, verbose_name='시청률')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_list', to='metadata.Content', verbose_name='작품')),
            ],
            options={
                'verbose_name': '영상',
                'verbose_name_plural': '영상목록',
                'db_table': 'video',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('participant_type', models.IntegerField(choices=[(0, '주연'), (1, '조연'), (2, '연출'), (3, '감독'), (4, '작가')], verbose_name='참여 종류')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='metadata.People', verbose_name='인물')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video', to='metadata.Video', verbose_name='영상')),
            ],
            options={
                'verbose_name': '참여정보',
                'verbose_name_plural': '참여정보목록',
                'db_table': 'participation',
            },
            bases=(libs.django.db.models.base_model.EqualizeMixin, libs.django.db.models.base_model.ChangeMixin, models.Model),
        ),
    ]
