# Generated by Django 2.2.6 on 2019-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20191031_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='name_original_foreign',
        ),
        migrations.AddField(
            model_name='people',
            name='name_original',
            field=models.CharField(blank=True, max_length=32, verbose_name='본명'),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '남자'), (1, '여자'), (65535, '기타')], null=True, verbose_name='성별'),
        ),
    ]
